apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: django-web-app-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx" 
spec:
  rules:
    - host: myminikube.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: django-web-app
                port:
                  number: 80

